// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dglm_scale_chunk
List dglm_scale_chunk(IntegerVector ptr, IntegerVector idx, NumericVector w, NumericMatrix W0t, NumericMatrix R0t, int K, double rho, double Q, IntegerVector pptr, IntegerVector pidx, NumericVector pw, int n0);
RcppExport SEXP _spCF_dglm_scale_chunk(SEXP ptrSEXP, SEXP idxSEXP, SEXP wSEXP, SEXP W0tSEXP, SEXP R0tSEXP, SEXP KSEXP, SEXP rhoSEXP, SEXP QSEXP, SEXP pptrSEXP, SEXP pidxSEXP, SEXP pwSEXP, SEXP n0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W0t(W0tSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type R0t(R0tSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type Q(QSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pptr(pptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pidx(pidxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pw(pwSEXP);
    Rcpp::traits::input_parameter< int >::type n0(n0SEXP);
    rcpp_result_gen = Rcpp::wrap(dglm_scale_chunk(ptr, idx, w, W0t, R0t, K, rho, Q, pptr, pidx, pw, n0));
    return rcpp_result_gen;
END_RCPP
}
// lwr_chunk_cpp
void lwr_chunk_cpp(List nb_id, List nb_dist, SEXP nb_id0_sexp, SEXP nb_dist0_sexp, IntegerVector sel_chunk, LogicalVector id_train_flag, NumericVector resid, NumericMatrix x, SEXP x0_sexp, NumericMatrix B_var, IntegerVector vc_cols, double band, int kernel_id, NumericMatrix b_all, NumericMatrix bv_inv_all, NumericMatrix pv_inv_all, SEXP b_all0_sexp, SEXP bv_inv_all0_sexp, SEXP pv_inv_all0_sexp, NumericMatrix b_old);
RcppExport SEXP _spCF_lwr_chunk_cpp(SEXP nb_idSEXP, SEXP nb_distSEXP, SEXP nb_id0_sexpSEXP, SEXP nb_dist0_sexpSEXP, SEXP sel_chunkSEXP, SEXP id_train_flagSEXP, SEXP residSEXP, SEXP xSEXP, SEXP x0_sexpSEXP, SEXP B_varSEXP, SEXP vc_colsSEXP, SEXP bandSEXP, SEXP kernel_idSEXP, SEXP b_allSEXP, SEXP bv_inv_allSEXP, SEXP pv_inv_allSEXP, SEXP b_all0_sexpSEXP, SEXP bv_inv_all0_sexpSEXP, SEXP pv_inv_all0_sexpSEXP, SEXP b_oldSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nb_id(nb_idSEXP);
    Rcpp::traits::input_parameter< List >::type nb_dist(nb_distSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nb_id0_sexp(nb_id0_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nb_dist0_sexp(nb_dist0_sexpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sel_chunk(sel_chunkSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type id_train_flag(id_train_flagSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type resid(residSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x0_sexp(x0_sexpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B_var(B_varSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type vc_cols(vc_colsSEXP);
    Rcpp::traits::input_parameter< double >::type band(bandSEXP);
    Rcpp::traits::input_parameter< int >::type kernel_id(kernel_idSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_all(b_allSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bv_inv_all(bv_inv_allSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pv_inv_all(pv_inv_allSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_all0_sexp(b_all0_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bv_inv_all0_sexp(bv_inv_all0_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pv_inv_all0_sexp(pv_inv_all0_sexpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_old(b_oldSEXP);
    lwr_chunk_cpp(nb_id, nb_dist, nb_id0_sexp, nb_dist0_sexp, sel_chunk, id_train_flag, resid, x, x0_sexp, B_var, vc_cols, band, kernel_id, b_all, bv_inv_all, pv_inv_all, b_all0_sexp, bv_inv_all0_sexp, pv_inv_all0_sexp, b_old);
    return R_NilValue;
END_RCPP
}
// lwr_chunk_glm_cpp
void lwr_chunk_glm_cpp(List nb_id, List nb_dist, SEXP nb_id0_sexp, SEXP nb_dist0_sexp, IntegerVector sel_chunk, LogicalVector id_train_flag, NumericVector resid, NumericVector w_obs, NumericMatrix x, SEXP x0_sexp, NumericMatrix B_var, IntegerVector vc_cols, double band, int kernel_id, NumericMatrix b_all, NumericMatrix bv_inv_all, NumericMatrix pv_inv_all, SEXP b_all0_sexp, SEXP bv_inv_all0_sexp, SEXP pv_inv_all0_sexp, NumericMatrix b_old);
RcppExport SEXP _spCF_lwr_chunk_glm_cpp(SEXP nb_idSEXP, SEXP nb_distSEXP, SEXP nb_id0_sexpSEXP, SEXP nb_dist0_sexpSEXP, SEXP sel_chunkSEXP, SEXP id_train_flagSEXP, SEXP residSEXP, SEXP w_obsSEXP, SEXP xSEXP, SEXP x0_sexpSEXP, SEXP B_varSEXP, SEXP vc_colsSEXP, SEXP bandSEXP, SEXP kernel_idSEXP, SEXP b_allSEXP, SEXP bv_inv_allSEXP, SEXP pv_inv_allSEXP, SEXP b_all0_sexpSEXP, SEXP bv_inv_all0_sexpSEXP, SEXP pv_inv_all0_sexpSEXP, SEXP b_oldSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nb_id(nb_idSEXP);
    Rcpp::traits::input_parameter< List >::type nb_dist(nb_distSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nb_id0_sexp(nb_id0_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nb_dist0_sexp(nb_dist0_sexpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sel_chunk(sel_chunkSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type id_train_flag(id_train_flagSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type resid(residSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w_obs(w_obsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x0_sexp(x0_sexpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B_var(B_varSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type vc_cols(vc_colsSEXP);
    Rcpp::traits::input_parameter< double >::type band(bandSEXP);
    Rcpp::traits::input_parameter< int >::type kernel_id(kernel_idSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_all(b_allSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bv_inv_all(bv_inv_allSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pv_inv_all(pv_inv_allSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_all0_sexp(b_all0_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bv_inv_all0_sexp(bv_inv_all0_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pv_inv_all0_sexp(pv_inv_all0_sexpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_old(b_oldSEXP);
    lwr_chunk_glm_cpp(nb_id, nb_dist, nb_id0_sexp, nb_dist0_sexp, sel_chunk, id_train_flag, resid, w_obs, x, x0_sexp, B_var, vc_cols, band, kernel_id, b_all, bv_inv_all, pv_inv_all, b_all0_sexp, bv_inv_all0_sexp, pv_inv_all0_sexp, b_old);
    return R_NilValue;
END_RCPP
}
// lwr_glm_fused_cpp
List lwr_glm_fused_cpp(NumericMatrix coords, NumericMatrix coords_cent, NumericVector resid, NumericVector w_obs, NumericMatrix x, IntegerVector id_train, NumericMatrix B_var, IntegerVector vc_cols, double band, int kernel_id, double threshold, int is_lm, SEXP coords0_sexp, SEXP x0_sexp);
RcppExport SEXP _spCF_lwr_glm_fused_cpp(SEXP coordsSEXP, SEXP coords_centSEXP, SEXP residSEXP, SEXP w_obsSEXP, SEXP xSEXP, SEXP id_trainSEXP, SEXP B_varSEXP, SEXP vc_colsSEXP, SEXP bandSEXP, SEXP kernel_idSEXP, SEXP thresholdSEXP, SEXP is_lmSEXP, SEXP coords0_sexpSEXP, SEXP x0_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coords_cent(coords_centSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type resid(residSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w_obs(w_obsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type id_train(id_trainSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B_var(B_varSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type vc_cols(vc_colsSEXP);
    Rcpp::traits::input_parameter< double >::type band(bandSEXP);
    Rcpp::traits::input_parameter< int >::type kernel_id(kernel_idSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type is_lm(is_lmSEXP);
    Rcpp::traits::input_parameter< SEXP >::type coords0_sexp(coords0_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x0_sexp(x0_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(lwr_glm_fused_cpp(coords, coords_cent, resid, w_obs, x, id_train, B_var, vc_cols, band, kernel_id, threshold, is_lm, coords0_sexp, x0_sexp));
    return rcpp_result_gen;
END_RCPP
}
// lwr_ds_chunk_cpp
void lwr_ds_chunk_cpp(List nb_id, List nb_dist, IntegerVector sel_chunk, NumericVector local_bands, int kernel_id, int vc, NumericVector resid_area, NumericVector X_area, NumericVector W_area, NumericVector a, IntegerVector agg_id, LogicalVector id_train_flag, NumericMatrix x, NumericVector B_var_col, double c_shrink, NumericMatrix b_all, NumericMatrix bv_inv_all, NumericMatrix pv_inv_all, NumericMatrix b_old);
RcppExport SEXP _spCF_lwr_ds_chunk_cpp(SEXP nb_idSEXP, SEXP nb_distSEXP, SEXP sel_chunkSEXP, SEXP local_bandsSEXP, SEXP kernel_idSEXP, SEXP vcSEXP, SEXP resid_areaSEXP, SEXP X_areaSEXP, SEXP W_areaSEXP, SEXP aSEXP, SEXP agg_idSEXP, SEXP id_train_flagSEXP, SEXP xSEXP, SEXP B_var_colSEXP, SEXP c_shrinkSEXP, SEXP b_allSEXP, SEXP bv_inv_allSEXP, SEXP pv_inv_allSEXP, SEXP b_oldSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nb_id(nb_idSEXP);
    Rcpp::traits::input_parameter< List >::type nb_dist(nb_distSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sel_chunk(sel_chunkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type local_bands(local_bandsSEXP);
    Rcpp::traits::input_parameter< int >::type kernel_id(kernel_idSEXP);
    Rcpp::traits::input_parameter< int >::type vc(vcSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type resid_area(resid_areaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X_area(X_areaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type W_area(W_areaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type agg_id(agg_idSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type id_train_flag(id_train_flagSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B_var_col(B_var_colSEXP);
    Rcpp::traits::input_parameter< double >::type c_shrink(c_shrinkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_all(b_allSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bv_inv_all(bv_inv_allSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pv_inv_all(pv_inv_allSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_old(b_oldSEXP);
    lwr_ds_chunk_cpp(nb_id, nb_dist, sel_chunk, local_bands, kernel_id, vc, resid_area, X_area, W_area, a, agg_id, id_train_flag, x, B_var_col, c_shrink, b_all, bv_inv_all, pv_inv_all, b_old);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spCF_dglm_scale_chunk", (DL_FUNC) &_spCF_dglm_scale_chunk, 12},
    {"_spCF_lwr_chunk_cpp", (DL_FUNC) &_spCF_lwr_chunk_cpp, 20},
    {"_spCF_lwr_chunk_glm_cpp", (DL_FUNC) &_spCF_lwr_chunk_glm_cpp, 21},
    {"_spCF_lwr_glm_fused_cpp", (DL_FUNC) &_spCF_lwr_glm_fused_cpp, 14},
    {"_spCF_lwr_ds_chunk_cpp", (DL_FUNC) &_spCF_lwr_ds_chunk_cpp, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_spCF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
