// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lwr_chunk_cpp
void lwr_chunk_cpp(List nb_id, List nb_dist, SEXP nb_id0_sexp, SEXP nb_dist0_sexp, IntegerVector sel_chunk, LogicalVector id_train_flag, NumericVector resid, NumericMatrix x, SEXP x0_sexp, NumericMatrix B_var, IntegerVector vc_cols, double band, int kernel_id, NumericMatrix b_all, NumericMatrix bv_inv_all, NumericMatrix pv_inv_all, SEXP b_all0_sexp, SEXP bv_inv_all0_sexp, SEXP pv_inv_all0_sexp, NumericMatrix b_old);
RcppExport SEXP _spCF_lwr_chunk_cpp(SEXP nb_idSEXP, SEXP nb_distSEXP, SEXP nb_id0_sexpSEXP, SEXP nb_dist0_sexpSEXP, SEXP sel_chunkSEXP, SEXP id_train_flagSEXP, SEXP residSEXP, SEXP xSEXP, SEXP x0_sexpSEXP, SEXP B_varSEXP, SEXP vc_colsSEXP, SEXP bandSEXP, SEXP kernel_idSEXP, SEXP b_allSEXP, SEXP bv_inv_allSEXP, SEXP pv_inv_allSEXP, SEXP b_all0_sexpSEXP, SEXP bv_inv_all0_sexpSEXP, SEXP pv_inv_all0_sexpSEXP, SEXP b_oldSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nb_id(nb_idSEXP);
    Rcpp::traits::input_parameter< List >::type nb_dist(nb_distSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nb_id0_sexp(nb_id0_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nb_dist0_sexp(nb_dist0_sexpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sel_chunk(sel_chunkSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type id_train_flag(id_train_flagSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type resid(residSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x0_sexp(x0_sexpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B_var(B_varSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type vc_cols(vc_colsSEXP);
    Rcpp::traits::input_parameter< double >::type band(bandSEXP);
    Rcpp::traits::input_parameter< int >::type kernel_id(kernel_idSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_all(b_allSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bv_inv_all(bv_inv_allSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pv_inv_all(pv_inv_allSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_all0_sexp(b_all0_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bv_inv_all0_sexp(bv_inv_all0_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pv_inv_all0_sexp(pv_inv_all0_sexpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_old(b_oldSEXP);
    lwr_chunk_cpp(nb_id, nb_dist, nb_id0_sexp, nb_dist0_sexp, sel_chunk, id_train_flag, resid, x, x0_sexp, B_var, vc_cols, band, kernel_id, b_all, bv_inv_all, pv_inv_all, b_all0_sexp, bv_inv_all0_sexp, pv_inv_all0_sexp, b_old);
    return R_NilValue;
END_RCPP
}
// lwr_chunk_glm_cpp
void lwr_chunk_glm_cpp(List nb_id, List nb_dist, SEXP nb_id0_sexp, SEXP nb_dist0_sexp, IntegerVector sel_chunk, LogicalVector id_train_flag, NumericVector resid, NumericVector w_obs, NumericMatrix x, SEXP x0_sexp, NumericMatrix B_var, IntegerVector vc_cols, double band, int kernel_id, NumericMatrix b_all, NumericMatrix bv_inv_all, NumericMatrix pv_inv_all, SEXP b_all0_sexp, SEXP bv_inv_all0_sexp, SEXP pv_inv_all0_sexp, NumericMatrix b_old);
RcppExport SEXP _spCF_lwr_chunk_glm_cpp(SEXP nb_idSEXP, SEXP nb_distSEXP, SEXP nb_id0_sexpSEXP, SEXP nb_dist0_sexpSEXP, SEXP sel_chunkSEXP, SEXP id_train_flagSEXP, SEXP residSEXP, SEXP w_obsSEXP, SEXP xSEXP, SEXP x0_sexpSEXP, SEXP B_varSEXP, SEXP vc_colsSEXP, SEXP bandSEXP, SEXP kernel_idSEXP, SEXP b_allSEXP, SEXP bv_inv_allSEXP, SEXP pv_inv_allSEXP, SEXP b_all0_sexpSEXP, SEXP bv_inv_all0_sexpSEXP, SEXP pv_inv_all0_sexpSEXP, SEXP b_oldSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nb_id(nb_idSEXP);
    Rcpp::traits::input_parameter< List >::type nb_dist(nb_distSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nb_id0_sexp(nb_id0_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nb_dist0_sexp(nb_dist0_sexpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sel_chunk(sel_chunkSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type id_train_flag(id_train_flagSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type resid(residSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w_obs(w_obsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x0_sexp(x0_sexpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B_var(B_varSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type vc_cols(vc_colsSEXP);
    Rcpp::traits::input_parameter< double >::type band(bandSEXP);
    Rcpp::traits::input_parameter< int >::type kernel_id(kernel_idSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_all(b_allSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bv_inv_all(bv_inv_allSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pv_inv_all(pv_inv_allSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_all0_sexp(b_all0_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bv_inv_all0_sexp(bv_inv_all0_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pv_inv_all0_sexp(pv_inv_all0_sexpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_old(b_oldSEXP);
    lwr_chunk_glm_cpp(nb_id, nb_dist, nb_id0_sexp, nb_dist0_sexp, sel_chunk, id_train_flag, resid, w_obs, x, x0_sexp, B_var, vc_cols, band, kernel_id, b_all, bv_inv_all, pv_inv_all, b_all0_sexp, bv_inv_all0_sexp, pv_inv_all0_sexp, b_old);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spCF_lwr_chunk_cpp", (DL_FUNC) &_spCF_lwr_chunk_cpp, 20},
    {"_spCF_lwr_chunk_glm_cpp", (DL_FUNC) &_spCF_lwr_chunk_glm_cpp, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_spCF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
