# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lwr_chunk_cpp <- function(nb_id, nb_dist, nb_id0_sexp, nb_dist0_sexp, sel_chunk, id_train_flag, resid, x, x0_sexp, B_var, vc_cols, band, kernel_id, b_all, bv_inv_all, pv_inv_all, b_all0_sexp, bv_inv_all0_sexp, pv_inv_all0_sexp, b_old) {
    invisible(.Call(`_spCF_lwr_chunk_cpp`, nb_id, nb_dist, nb_id0_sexp, nb_dist0_sexp, sel_chunk, id_train_flag, resid, x, x0_sexp, B_var, vc_cols, band, kernel_id, b_all, bv_inv_all, pv_inv_all, b_all0_sexp, bv_inv_all0_sexp, pv_inv_all0_sexp, b_old))
}

lwr_chunk_glm_cpp <- function(nb_id, nb_dist, nb_id0_sexp, nb_dist0_sexp, sel_chunk, id_train_flag, resid, w_obs, x, x0_sexp, B_var, vc_cols, band, kernel_id, b_all, bv_inv_all, pv_inv_all, b_all0_sexp, bv_inv_all0_sexp, pv_inv_all0_sexp, b_old) {
    invisible(.Call(`_spCF_lwr_chunk_glm_cpp`, nb_id, nb_dist, nb_id0_sexp, nb_dist0_sexp, sel_chunk, id_train_flag, resid, w_obs, x, x0_sexp, B_var, vc_cols, band, kernel_id, b_all, bv_inv_all, pv_inv_all, b_all0_sexp, bv_inv_all0_sexp, pv_inv_all0_sexp, b_old))
}

